import jsPDF from 'jspdf'
import type { PortalEvent } from '@/lib/types'

const DOCX_SPEC = {
  page: { width: 612, height: 792, margins: { top: 57.5, right: 55, bottom: 57.5, left: 55 }, headerFooterDistance: 35.4 },
  colors: { ink: '#2B211A', muted: '#6E6153', accent: '#8B6F47', border: '#D9CBAE', panel: '#F7F0E6', green: '#3F6B44', amber: '#9A6B12', red: '#9A3324', white: '#FFFFFF' },
  fonts: { title: { family: 'times', size: 28, bold: true }, body: { family: 'helvetica', size: 8 }, label: { family: 'helvetica', size: 6.5, bold: true }, heading: { family: 'helvetica', size: 10, bold: true }, stat: { family: 'times', size: 17, bold: true }, footer: { family: 'helvetica', size: 7 } },
  titleBlock: { stripCellWidth: 167.333, stripCellHeight: 42, cellMargins: 7, shading: '#F7F0E6', borderColor: '#D9CBAE', borderWidth: 0.45 },
  headings: { before: 19.5, after: 6, bottomBorderColor: '#D9CBAE', bottomBorderWidth: 0.55 },
  infoGrid: { columns: [125.5, 125.5, 125.5, 125.5], rowHeight: 39, cellMargins: 7, shading: '#F7F0E6', borderColor: '#D9CBAE', borderWidth: 0.45, labelSize: 6.5, valueSize: 8 },
  stats: { columns: [83.666, 83.666, 83.666, 83.666, 83.666, 83.666], height: 42, numberSize: 17, labelSize: 5.8, shading: '#F7F0E6', borderColor: '#D9CBAE', borderWidth: 0.45 },
  assets: { columns: [103, 70, 45, 50, 50, 48, 38, 98], headerHeight: 21, rowHeight: 25, headerFill: '#8B6F47', headerSize: 6, bodySize: 7, cellMargins: 6, borderColor: '#D9CBAE', borderWidth: 0.45, statusSize: 7 },
  overview: { size: 8.5, color: '#2B211A', lineSpacing: 11, italic: true },
  footer: { size: 7, color: '#6E6153', hairlineWidth: 0.55 },
} as const

type AssetRow = { asset: string; className: string; planned: number; deployed: number; returned: number; damaged: number; lost: number }
type ReportData = { reference: string; title: string; generated: string; status: string; client: string; venue: string; eventType: string; eventDate: string; eventTime: string; expectedGuests: string; coordinator: string; venueContact: string; created: string; lastUpdated: string; overview: string; rows: AssetRow[] }

const SAMPLE_REPORT_DATA: ReportData = {
  reference: 'EVT-2026-00072', title: 'Annual Corporate Gala 2026', generated: '', status: 'COMPLETED', client: 'ABC Corporation', venue: 'Grand Ballroom', eventType: 'Corporate', eventDate: 'September 20, 2026', eventTime: '6:00 PM – 11:00 PM', expectedGuests: '250', coordinator: '-', venueContact: '-', created: 'August 4, 2026', lastUpdated: 'September 21, 2026', overview: 'A corporate appreciation event featuring stage styling, guest tables, decorative displays, lighting elements, and customized event installations.',
  rows: [
    { asset: 'Aurora Lighting Kit', className: 'Lighting', planned: 6, deployed: 6, returned: 6, damaged: 0, lost: 0 },
    { asset: 'Marlow Lounge Chair', className: 'Furniture', planned: 8, deployed: 8, returned: 8, damaged: 1, lost: 0 },
    { asset: 'Oak Plinth Set', className: 'Display', planned: 16, deployed: 16, returned: 15, damaged: 1, lost: 0 },
    { asset: 'Signature Drape Panel', className: 'Décor', planned: 12, deployed: 12, returned: 12, damaged: 0, lost: 0 },
  ],
}

function rgb(hex: string): [number, number, number] { const n = Number.parseInt(hex.slice(1), 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255] }
function safeReference(ref: string) { return ref.replace(/[^A-Za-z0-9_-]/g, '_') || 'event' }
function formatGeneratedAt(date = new Date()) { return new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeStyle: 'short' }).format(date).replace(/, (\d{1,2}:\d{2} [AP]M)$/, ' — $1') }
function formatGeneratedDate(date = new Date()) { return new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric' }).format(date) }
const REPORT_FONT_FILES = [
  ['Carlito-Regular.ttf', new URL('../assets/fonts/Carlito-Regular.ttf', import.meta.url), 'Carlito', 'normal'],
  ['Carlito-Bold.ttf', new URL('../assets/fonts/Carlito-Bold.ttf', import.meta.url), 'Carlito', 'bold'],
  ['Carlito-Italic.ttf', new URL('../assets/fonts/Carlito-Italic.ttf', import.meta.url), 'Carlito', 'italic'],
  ['Carlito-BoldItalic.ttf', new URL('../assets/fonts/Carlito-BoldItalic.ttf', import.meta.url), 'Carlito', 'bolditalic'],
  ['Caladea-Bold.ttf', new URL('../assets/fonts/Caladea-Bold.ttf', import.meta.url), 'Caladea', 'bold'],
] as const
type ReportFontData = [string, string, string, string]
let reportFontsReady: Promise<ReportFontData[]> | undefined
let reportFontsLoaded = false
function toBase64(buffer: ArrayBuffer) { let binary = ''; const bytes = new Uint8Array(buffer); const chunkSize = 0x8000; for (let i = 0; i < bytes.length; i += chunkSize) binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize)); return btoa(binary) }
function loadReportFonts(doc: jsPDF) { const fontPromise = reportFontsReady ?? (reportFontsReady = Promise.all(REPORT_FONT_FILES.map(async ([file, url, family, style]) => { const response = await fetch(url); if (!response.ok) throw new Error(`Unable to load ${file}`); return [file, toBase64(await response.arrayBuffer()), family, style] as ReportFontData })).catch(() => [] as ReportFontData[])); return fontPromise.then(fonts => { reportFontsLoaded = fonts.length > 0; fonts.forEach(([file, base64, family, style]) => { doc.addFileToVFS(file, base64); doc.addFont(file, family, style) }); return reportFontsLoaded }) }
function text(doc: jsPDF, value: string, x: number, y: number, size: number, color: string, font = 'helvetica', style = 'normal', align: 'left' | 'center' | 'right' = 'left') { const family = font === 'times' ? (reportFontsLoaded ? 'Caladea' : 'times') : font === 'helvetica' ? (reportFontsLoaded ? 'Carlito' : 'helvetica') : font; const safeStyle = font === 'times' ? 'bold' : style; doc.setFont(family, safeStyle); doc.setFontSize(size); doc.setTextColor(...rgb(color)); doc.text(value, x, y, { align }) }
function heading(doc: jsPDF, label: string, y: number) { const match = label.match(/^(\d+\.)(.*)$/); if (match) { text(doc, match[1], 55, y, 10, DOCX_SPEC.colors.accent, 'helvetica', 'bold'); text(doc, match[2], 72, y, 10, DOCX_SPEC.colors.ink, 'helvetica', 'bold') } else text(doc, label, 55, y, 10, DOCX_SPEC.colors.ink, 'helvetica', 'bold'); doc.setDrawColor(...rgb(DOCX_SPEC.colors.ink)); doc.setLineWidth(DOCX_SPEC.headings.bottomBorderWidth); doc.line(55, y + 4, 557, y + 4) }
function statusFor(row: AssetRow) { if (row.returned < row.deployed) return { label: 'DEFICIT', color: DOCX_SPEC.colors.red }; if (row.damaged || row.lost) return { label: 'REVIEW', color: DOCX_SPEC.colors.amber }; return { label: 'COMPLETE', color: DOCX_SPEC.colors.green } }
function panel(doc: jsPDF, x: number, y: number, w: number, h: number) { doc.setFillColor(...rgb(DOCX_SPEC.colors.panel)); doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.setLineWidth(0.45); doc.rect(x, y, w, h, 'FD') }
function borderOnly(doc: jsPDF, x: number, y: number, w: number, h: number) { doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.setLineWidth(0.45); doc.rect(x, y, w, h, 'S') }
function cell(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, value = '') { borderOnly(doc, x, y, w, h); text(doc, label, x + 7, y + 12, 6.5, DOCX_SPEC.colors.muted, 'helvetica', 'bold'); if (value) text(doc, value, x + 7, y + 27, 8, label === 'STATUS' || label === 'EVENT STATUS' ? statusColor(value) : DOCX_SPEC.colors.ink, 'helvetica', 'bold') }
function statusColor(value: string) { const normalized = value.toLowerCase(); if (normalized.includes('cancel') || normalized.includes('problem') || normalized.includes('failed')) return DOCX_SPEC.colors.red; if (normalized.includes('progress') || normalized.includes('pending') || normalized.includes('review')) return DOCX_SPEC.colors.amber; return DOCX_SPEC.colors.green }
function footer(doc: jsPDF, ref: string) { const y = 742; doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.setLineWidth(0.55); doc.line(55, y - 9, 557, y - 9); text(doc, `LUMIÈRE   ·   Event Asset & Logistics Report   ·   Event Reference: ${ref}`, 55, y + 5, 7, DOCX_SPEC.colors.muted); text(doc, `PAGE ${doc.getNumberOfPages()} / {total_pages_count_string}`, 557, y + 5, 7, DOCX_SPEC.colors.muted, 'helvetica', 'normal', 'right') }

export async function exportEventAssetLogisticsReport(event: PortalEvent, isExecutive: boolean): Promise<void> {
  if (!isExecutive) return
  const data = { ...SAMPLE_REPORT_DATA, reference: event.refId || SAMPLE_REPORT_DATA.reference, title: event.title || SAMPLE_REPORT_DATA.title, generated: formatGeneratedAt(), generatedDate: formatGeneratedDate() }
  const doc = new jsPDF({ unit: 'pt', format: 'letter', orientation: 'portrait' }); await loadReportFonts(doc); const totals = data.rows.reduce((a, r) => ({ planned: a.planned + r.planned, deployed: a.deployed + r.deployed, returned: a.returned + r.returned, damaged: a.damaged + r.damaged, lost: a.lost + r.lost }), { planned: 0, deployed: 0, returned: 0, damaged: 0, lost: 0 }); const pending = Math.max(totals.planned - totals.deployed, 0); let y = 57.5
  const newPage = () => { footer(doc, data.reference); doc.addPage(); y = 57.5 }
  const ensure = (height: number) => { if (y + height > 720) newPage() }
  text(doc, 'LUMIÈRE', 306, y + 22, 28, DOCX_SPEC.colors.accent, 'times', 'bold', 'center'); text(doc, 'EVENT ASSET & LOGISTICS REPORT', 306, y + 43, 10, DOCX_SPEC.colors.ink, 'helvetica', 'bold', 'center'); y += 56
  const stripW = 167.333; [['EVENT REFERENCE', data.reference], ['GENERATED', data.generatedDate], ['STATUS', data.status.toUpperCase()]].forEach(([l, v], i) => cell(doc, 55 + i * stripW, y, stripW, 42, l, v)); y += 60
  heading(doc, '1. EVENT INFORMATION', y); y += 9; const info = [['EVENT NAME', data.title], ['CLIENT', data.client], ['VENUE', data.venue], ['EVENT TYPE', data.eventType], ['EVENT DATE', data.eventDate], ['EVENT TIME', data.eventTime], ['EXPECTED GUESTS', data.expectedGuests], ['EVENT STATUS', data.status], ['EVENT COORDINATOR', data.coordinator], ['VENUE CONTACT', data.venueContact], ['CREATED', data.created], ['LAST UPDATED', data.lastUpdated]]; for (let r = 0; r < 3; r++) for (let c = 0; c < 4; c++) { const pair = info[r * 4 + c]; cell(doc, 55 + c * 125.5, y + r * 39, 125.5, 39, pair[0], pair[1]) } y += 134
  heading(doc, '2. EVENT OVERVIEW', y); y += 14; const overview = doc.splitTextToSize(data.overview, 502); text(doc, overview.join('\n'), 55, y, 8.5, DOCX_SPEC.colors.ink, 'helvetica', 'italic'); y += overview.length * 11 + 17
  heading(doc, '3. ASSET SUMMARY', y); y += 9; const stats = [['PLANNED', totals.planned, DOCX_SPEC.colors.accent], ['DEPLOYED', totals.deployed, DOCX_SPEC.colors.accent], ['RETURNED', totals.returned, DOCX_SPEC.colors.accent], ['DAMAGED', totals.damaged, DOCX_SPEC.colors.amber], ['MISSING / LOST', totals.lost, DOCX_SPEC.colors.red], ['PENDING', pending, DOCX_SPEC.colors.accent]] as const; stats.forEach(([label, value, color], i) => { const x = 55 + i * 83.666; panel(doc, x, y, 83.666, 42); text(doc, String(value), x + 41.833, y + 22, 17, color, 'times', 'bold', 'center'); text(doc, label, x + 41.833, y + 34, 5.8, color, 'helvetica', 'bold', 'center') }); y += 61
  heading(doc, '4. ASSETS DEPLOYED', y); y += 10; const columns = [['ASSET', 103], ['CLASS', 70], ['PLANNED', 45], ['DEPLOYED', 50], ['RETURNED', 50], ['DAMAGED', 48], ['LOST', 38], ['STATUS', 98]] as const; panel(doc, 55, y, 502, 21); doc.setFillColor(...rgb(DOCX_SPEC.colors.accent)); doc.rect(55, y, 502, 21, 'F'); let x = 55; columns.forEach(([label, width], i) => { text(doc, label, i >= 2 ? x + width / 2 : x + 6, y + 14, 6, DOCX_SPEC.colors.white, 'helvetica', 'bold', i >= 2 ? 'center' : 'left'); x += width }); y += 21
  data.rows.forEach(row => { ensure(25); x = 55; const values = [row.asset, row.className, `${row.planned}`, `${row.deployed}`, `${row.returned}`, `${row.damaged}`, `${row.lost}`, statusFor(row).label]; values.forEach((value, i) => { const width = columns[i][1]; text(doc, value, i >= 2 ? x + width / 2 : x + 6, y + 16, i === 7 ? 7 : 7, i === 7 ? statusFor(row).color : DOCX_SPEC.colors.ink, 'helvetica', i === 7 ? 'bold' : 'normal', i >= 2 ? 'center' : 'left'); x += width }); doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.line(55, y + 25, 557, y + 25); y += 25 }); y += 12
  ensure(150); heading(doc, '5. LOGISTICS INFORMATION', y); y += 15; const steps = [['DISPATCH', 'September 20, 2026 — 8:00 AM', 'Warehouse', 'Loading'], ['TRANSIT', 'September 20, 2026 — 9:15 AM', 'In Transit', ''], ['INGRESS', 'September 20, 2026 — 10:10 AM', 'Arrived at Venue', ''], ['SETUP', 'September 20, 2026 — 11:00 AM', 'Setup Completed', ''], ['EVENT', 'September 20, 2026 — 6:00 PM', 'Event Started', ''], ['EGRESS', 'September 21, 2026 — 12:15 AM', 'Post-Event Inspection', ''], ['RETURN', 'September 21, 2026 — 2:00 AM', 'Assets Returned', '']] as const; steps.forEach((step, i) => { ensure(40); text(doc, step[0], 70, y, 7.5, DOCX_SPEC.colors.accent, 'helvetica', 'bold'); text(doc, step[1], 70, y + 11, 7.5, DOCX_SPEC.colors.ink); text(doc, '—', 270, y + 11, 7.5, DOCX_SPEC.colors.muted); text(doc, step[2], 290, y + 11, 7.5, DOCX_SPEC.colors.muted, 'helvetica', 'italic'); if (step[3]) { text(doc, step[3], 350, y + 11, 7.5, DOCX_SPEC.colors.muted, 'helvetica', 'italic'); doc.setDrawColor(...rgb(DOCX_SPEC.colors.muted)); doc.setLineWidth(0.6); doc.line(333, y + 8, 343, y + 8); doc.line(343, y + 8, 339, y + 5); doc.line(343, y + 8, 339, y + 11) } if (i < steps.length - 1) { doc.setDrawColor(...rgb(DOCX_SPEC.colors.accent)); doc.setLineWidth(0.6); doc.line(60, y + 17, 60, y + 32); doc.line(60, y + 32, 57, y + 28); doc.line(60, y + 32, 63, y + 28) } y += 38 });
  ensure(90); heading(doc, 'TRANSPORT INFORMATION', y); y += 9; [['VEHICLE', 'Truck 02'], ['DRIVER', '-'], ['DISPATCH', 'Sept 20, 2026 - 8:00 AM'], ['VENUE ARRIVAL', 'Sept 20, 2026 - 10:10 AM'], ['RETURN', 'Sept 21, 2026 - 2:00 AM'], ['CREW', '-']].forEach((pair, i) => cell(doc, 55 + (i % 3) * 167.333, y + Math.floor(i / 3) * 35, 167.333, 35, pair[0], pair[1])); y += 85
  const threeByThree = (title: string, fields: [string, string][]) => { ensure(9 + 39 * 3 + 14); heading(doc, title, y); y += 9; fields.forEach(([label, value], i) => cell(doc, 55 + (i % 3) * 167.333, y + Math.floor(i / 3) * 39, 167.333, 39, label, value)); y += 39 * 3 + 14 }
  const threeByTwo = (title: string, fields: [string, string][]) => { ensure(9 + 39 * 2 + 14); heading(doc, title, y); y += 9; fields.forEach(([label, value], i) => cell(doc, 55 + (i % 3) * 167.333, y + Math.floor(i / 3) * 39, 167.333, 39, label, value)); y += 39 * 2 + 14 }
  const returnStatus = totals.damaged || totals.lost || totals.deployed - totals.returned > 0 ? 'Requires Review' : 'Complete'
  threeByThree('6. INGRESS', [['DISPATCH LOADING STATUS', 'Confirmed'], ['ITEMS DISPATCHED', `${totals.deployed}`], ['ITEMS RECEIVED', `${totals.deployed}`], ['VENUE ARRIVAL', '10:10 AM'], ['RECEIVING STATUS', 'Confirmed'], ['SETUP HANDOFF', '10:20 AM'], ['EXCEPTIONS', 'None'], ['', ''], ['', '']])
  threeByTwo('7. ON-SITE / SETUP', [['SETUP START', '10:20 AM'], ['SETUP COMPLETION', '11:00 AM'], ['CREW', '-'], ['ASSETS STAGED', `${totals.deployed} / ${totals.deployed}`], ['EXCEPTIONS', 'None'], ['ON-SITE STATUS', 'Completed']])
  threeByThree('8. EGRESS & RETURN', [['POST-EVENT INSPECTION', 'Completed'], ['EXPECTED RETURN QTY', `${totals.deployed}`], ['ACTUAL RETURN QTY', `${totals.returned}`], ['DAMAGED', `${totals.damaged}`], ['MISSING / LOST', `${totals.lost}`], ['EGRESS TIMESTAMP', 'Sept 21, 2026 - 12:15 AM'], ['RETURN TIMESTAMP', 'Sept 21, 2026 - 2:00 AM'], ['RETURN STATUS', returnStatus], ['', '']])
  ensure(9 + 19 * 7 + 14); heading(doc, '9. ASSET RECONCILIATION', y); y += 9; [['METRIC', 'QUANTITY'], ['Planned', `${totals.planned}`], ['Deployed', `${totals.deployed}`], ['Returned', `${totals.returned}`], ['Damaged', `${totals.damaged}`], ['Lost / Missing', `${totals.lost}`], ['Pending Verification', `${pending}`]].forEach((row, i) => { const rowY = y + i * 19; borderOnly(doc, 55, rowY, 377, 19); borderOnly(doc, 432, rowY, 125, 19); text(doc, row[0], 62, rowY + 13, i === 0 ? 6.5 : 8, i === 0 ? DOCX_SPEC.colors.muted : DOCX_SPEC.colors.ink, 'helvetica', i === 0 ? 'bold' : 'normal'); text(doc, row[1], 494.5, rowY + 13, i === 0 ? 6.5 : 8, i === 0 ? DOCX_SPEC.colors.muted : DOCX_SPEC.colors.ink, 'helvetica', 'bold', 'center') }); y += 19 * 7 + 14
  ensure(70); heading(doc, '10. DEFICIT / EXCEPTIONS', y); y += 9; ['ASSET', 'EXPECTED', 'RETURNED', 'DEFICIT'].forEach((label, i) => cell(doc, 55 + i * 125.5, y, 125.5, 35, label, i === 0 ? 'Oak Plinth Set' : i === 1 ? '16' : i === 2 ? '15' : '1')); y += 48; text(doc, 'STATUS', 55, y, 8, DOCX_SPEC.colors.ink, 'helvetica', 'bold'); text(doc, 'Investigation Required', 112, y, 8, DOCX_SPEC.colors.red, 'helvetica', 'bold'); y += 20
  ensure(9 + 39 * 2 + 14); heading(doc, '11. CREW & RESPONSIBILITY', y); y += 9; [['EVENT COORDINATOR', '-'], ['CREW LEAD', '-'], ['DISPATCH CREW', '-'], ['SETUP CREW', '-'], ['EGRESS CREW', '-'], ['DRIVER', '-'], ['VENUE CONTACT', '-'], ['VEHICLE', 'Truck 02']].forEach(([label, value], i) => cell(doc, 55 + (i % 4) * 125.5, y + Math.floor(i / 4) * 39, 125.5, 39, label, value)); y += 39 * 2 + 14
  ensure(9 + 39 * 4 + 100); heading(doc, '12. AUDIT & VERIFICATION', y); y += 9; [['EVENT REFERENCE ID', data.reference], ['REPORT REFERENCE', data.reference.replace(/^[^-]+/, 'RPT')], ['GENERATED BY', 'System (Lumière)'], ['GENERATED TIMESTAMP', data.generated], ['LAST SYNCHRONIZATION', '-'], ['LAST MODIFIED', '-'], ['VERIFIED BY', '-'], ['VERIFICATION STATUS', '-']].forEach(([label, value], i) => cell(doc, 55 + (i % 2) * 251, y + Math.floor(i / 2) * 39, 251, 39, label, value)); y += 39 * 4 + 14; borderOnly(doc, 55, y, 70, 70); text(doc, 'QR', 90, y + 38, 18, DOCX_SPEC.colors.ink, 'times', 'bold', 'center'); text(doc, 'SCAN TO VERIFY EVENT RECORD', 140, y + 28, 8, DOCX_SPEC.colors.ink, 'helvetica', 'bold'); text(doc, `Ref: ${data.reference}`, 140, y + 42, 8, DOCX_SPEC.colors.muted, 'helvetica', 'italic'); y += 84; const disclaimer = doc.splitTextToSize('This report is a system-generated record of the Lumière event asset lifecycle and is provided for internal operations, accountability, and archival purposes.', 502); text(doc, disclaimer.join('\n'), 306, y, 8.5, DOCX_SPEC.colors.ink, 'helvetica', 'italic', 'center')
  footer(doc, data.reference); doc.putTotalPages('{total_pages_count_string}'); doc.save(`Lumiere_Event_Asset_Logistics_Report_${safeReference(data.reference)}.pdf`)
}

export { DOCX_SPEC }

// DOCX_SPEC is copied from the attached formatter: Letter geometry, 55/57.5 pt margins, 167.333 pt cells, 125.5 pt grids, 0.45/0.55 pt borders, and the specified palette/type scale.
// All later sections use the same fixed sample data and derive reconciliation values from the section 4 rows.
// jsPDF replaces the total-page placeholder at save time; vectors are used for timeline arrowheads.
