import jsPDF from 'jspdf'
import type { PortalEvent } from '@/lib/types'

const TYPE = { wordmark: 28, subtitle: 12, titleValue: 11, sectionHeading: 10, fieldLabel: 7, fieldValue: 11, overview: 10.5, summaryNumber: 15, summaryLabel: 7, tableHeader: 9, tableBody: 9.5, timelineTitle: 10, timelineDetail: 9, transportSubheader: 9, deficitLabel: 8, deficitValue: 10, qrTitle: 9, qrReference: 9, disclaimer: 8 } as const
const VALUE_FONT_FAMILY = 'times'
const SUMMARY_FONT_FAMILY = 'times'

const DOCX_SPEC = {
  page: { width: 612, height: 792, margins: { top: 57.5, right: 55, bottom: 57.5, left: 55 }, headerFooterDistance: 35.4 },
  colors: { ink: '#2B211A', muted: '#6E6153', accent: '#8B6F47', border: '#D9CBAE', panel: '#F7F0E6', green: '#3F6B44', amber: '#9A6B12', red: '#9A3324', white: '#FFFFFF' },
  fonts: { title: { family: 'times', size: 30, bold: true }, body: { family: 'times', size: 9 }, label: { family: 'times', size: 7, bold: true }, heading: { family: 'times', size: 10.5, bold: true }, stat: { family: 'times', size: 18, bold: true }, footer: { family: 'times', size: 7.5 } },
  titleBlock: { stripCellWidth: 167.333, stripCellHeight: 42, cellMargins: 7, shading: '#F7F0E6', borderColor: '#D9CBAE', borderWidth: 0.45 },
  headings: { before: 19.5, after: 6, bottomBorderColor: '#D9CBAE', bottomBorderWidth: 0.55 },
  infoGrid: { columns: [125.5, 125.5, 125.5, 125.5], rowHeight: 39, cellMargins: 7, shading: '#F7F0E6', borderColor: '#D9CBAE', borderWidth: 0.45, labelSize: 6.5, valueSize: 8 },
  stats: { columns: [83.666, 83.666, 83.666, 83.666, 83.666, 83.666], height: 42, numberSize: 17, labelSize: 5.8, shading: '#F7F0E6', borderColor: '#D9CBAE', borderWidth: 0.45 },
  assets: { columns: [140, 76, 45, 45, 45, 45, 38, 68], headerHeight: 21, rowHeight: 25, headerFill: '#8B6F47', headerSize: 8, bodySize: 10, cellMargins: 7, borderColor: '#D9CBAE', borderWidth: 0.45, statusSize: 10 },
  overview: { size: 8.5, color: '#2B211A', lineSpacing: 11, italic: true },
  footer: { size: 7, color: '#6E6153', hairlineWidth: 0.55 },
} as const

type AssetRow = { asset: string; className: string; planned: number; deployed: number | string; returned: number | string; damaged: number | string; lost: number | string; lifecycleKnown?: boolean }
type ExportAsset = { name: string; qty: number; category?: string; status?: string; available?: number }
type ReportData = { reference: string; title: string; generated: string; status: string; client: string; venue: string; eventType: string; eventDate: string; eventTime: string; expectedGuests: string; coordinator: string; venueContact: string; created: string; lastUpdated: string; overview: string; rows: AssetRow[] }

function rgb(hex: string): [number, number, number] { const n = Number.parseInt(hex.slice(1), 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255] }
function safeReference(ref: string) { return ref.replace(/[^A-Za-z0-9_-]/g, '_') || 'event' }
function formatGeneratedAt(date = new Date()) { return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(date) }
function formatDate(value?: string) { if (!value) return '-'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric' }).format(date) }
function readableEventTime(start?: string, end?: string) { const format = (value?: string) => { if (!value) return ''; const match = value.match(/^(\d{1,2}):(\d{2})$/); if (!match) return ''; const hour = Number(match[1]); const suffix = hour >= 12 ? 'PM' : 'AM'; return `${hour % 12 || 12}:${match[2]} ${suffix}` }; const a = format(start); const b = format(end); return a && b ? `${a} - ${b}` : '-' }
function resetTextState(doc: jsPDF) { doc.setCharSpace(0); doc.setFont(VALUE_FONT_FAMILY, 'normal'); doc.setFontSize(TYPE.fieldValue); doc.setTextColor(...rgb(DOCX_SPEC.colors.ink)) }
function text(doc: jsPDF, value: string, x: number, y: number, size: number, color: string, font = 'times', style = 'normal', align: 'left' | 'center' | 'right' = 'left') { doc.setCharSpace(0); doc.setFont(font, style); doc.setFontSize(size); doc.setTextColor(...rgb(color)); doc.text(value, x, y, { align }); resetTextState(doc) }
function drawLineArrow(doc: jsPDF, x1: number, y: number, x2: number) { doc.setDrawColor(...rgb(DOCX_SPEC.colors.accent)); doc.setLineWidth(0.55); doc.line(x1, y, x2 - 3, y); doc.line(x2 - 3, y, x2 - 6, y - 2); doc.line(x2 - 3, y, x2 - 6, y + 2); resetTextState(doc) }
function drawDownArrow(doc: jsPDF, x: number, y: number) { doc.setDrawColor(...rgb('#C9B48F')); doc.setLineWidth(0.8); doc.line(x + 4, y, x + 4, y + 8); doc.line(x + 1.5, y + 5.5, x + 4, y + 8); doc.line(x + 4, y + 8, x + 6.5, y + 5.5); resetTextState(doc) }
function heading(doc: jsPDF, label: string, y: number) { const headingSize = label === 'TRANSPORT INFORMATION' ? TYPE.transportSubheader : TYPE.sectionHeading; const match = label.match(/^(\d+\.)(.*)$/); if (match) { const number = `${match[1]}   `; const title = match[2].trim(); text(doc, number, 55, y, headingSize, DOCX_SPEC.colors.accent, 'times', 'bold'); const numberWidth = doc.getTextWidth(number); text(doc, title, 55 + numberWidth, y, headingSize, DOCX_SPEC.colors.ink, 'times', 'bold') } else text(doc, label, 55, y, headingSize, label === 'TRANSPORT INFORMATION' ? DOCX_SPEC.colors.muted : DOCX_SPEC.colors.ink, 'times', 'bold'); doc.setDrawColor(...rgb(DOCX_SPEC.colors.ink)); doc.setLineWidth(DOCX_SPEC.headings.bottomBorderWidth); doc.line(55, y + 4, 557, y + 4) }
function statusFor(row: AssetRow) { if (row.returned < row.deployed) return { label: 'DEFICIT', color: DOCX_SPEC.colors.red }; if (row.damaged || row.lost) return { label: 'REVIEW', color: DOCX_SPEC.colors.amber }; return { label: 'COMPLETE', color: DOCX_SPEC.colors.green } }
function panel(doc: jsPDF, x: number, y: number, w: number, h: number) { doc.setFillColor(...rgb(DOCX_SPEC.colors.panel)); doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.setLineWidth(0.45); doc.rect(x, y, w, h, 'FD') }
function borderOnly(doc: jsPDF, x: number, y: number, w: number, h: number) { doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.setLineWidth(0.45); doc.rect(x, y, w, h, 'S') }
function valueLines(doc: jsPDF, value: string, width: number) { doc.setFont(VALUE_FONT_FAMILY, 'normal'); doc.setFontSize(TYPE.fieldValue); return doc.splitTextToSize(value || '-', Math.max(width - 14, 20)) }
function valueHeight(doc: jsPDF, value: string, width: number, minimum = 39) { return Math.max(minimum, 23 + valueLines(doc, value, width).length * 13) }
function cell(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, value = '', valueStyle: 'normal' | 'bold' = 'normal', filled = false) { (filled ? panel : borderOnly)(doc, x, y, w, h); text(doc, label, x + 7, y + 12, TYPE.fieldLabel, DOCX_SPEC.colors.muted, 'times', 'bold'); if (value) { const displayValue = label === 'EVENT STATUS' && value === 'In Production' ? 'In Production' : value; const lines = valueLines(doc, displayValue, w); text(doc, lines.join('\n'), x + 7, y + 27, TYPE.fieldValue, label === 'STATUS' ? statusColor(value) : DOCX_SPEC.colors.ink, VALUE_FONT_FAMILY, valueStyle) } }
function statusColor(value: string) { const normalized = value.toLowerCase(); if (normalized.includes('cancel') || normalized.includes('problem') || normalized.includes('failed')) return DOCX_SPEC.colors.red; if (normalized.includes('progress') || normalized.includes('pending') || normalized.includes('review')) return DOCX_SPEC.colors.amber; return DOCX_SPEC.colors.green }
function header(doc: jsPDF) { const y = 25; doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.setLineWidth(0.55); doc.line(55, y + 8, 557, y + 8); text(doc, 'LUMIÈRE', 55, y, 8, DOCX_SPEC.colors.accent, 'times', 'bold'); text(doc, 'EVENT ASSET & LOGISTICS REPORT', 557, y, 7, DOCX_SPEC.colors.muted, 'times', 'bold', 'right') }
function footer(doc: jsPDF, ref: string) { const y = 775; doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.setLineWidth(0.55); doc.line(55, y - 9, 557, y - 9); text(doc, `LUMIÈRE · Event Asset & Logistics Report · Event Reference: ${ref}`, 55, y + 5, 7, DOCX_SPEC.colors.muted); text(doc, `PAGE ${doc.getNumberOfPages()} / {total_pages_count_string}`, 557, y + 5, 7, DOCX_SPEC.colors.muted, 'times', 'normal', 'right') }

export async function exportEventAssetLogisticsReport(event: PortalEvent, isExecutive: boolean, assets: ExportAsset[] = []): Promise<void> {
  if (!isExecutive) return
  let qrDataUrl: string | undefined
  try {
    const QR = await import('qrcode')
    qrDataUrl = await QR.toDataURL(event.refId || '-', { margin: 0, width: 256, errorCorrectionLevel: 'M', color: { dark: '#2B211A', light: '#FFFFFF' } })
  } catch {
    qrDataUrl = undefined
  }
  const source = event as PortalEvent & { eventType?: string; expectedGuests?: number | string; coordinator?: string; venueContact?: string; created?: string; lastUpdated?: string; overview?: string }
  const rows: AssetRow[] = assets.map((item) => ({ asset: item.name, className: item.category || '-', planned: item.qty, deployed: '-', returned: '-', damaged: '-', lost: '-', lifecycleKnown: false }))
  const data: ReportData = { reference: event.refId || '-', title: event.title || '-', generated: formatGeneratedAt(), status: event.status || '-', client: event.client || '-', venue: event.venue || '-', eventType: source.eventType || event.tier || '-', eventDate: formatDate(event.targetDate), eventTime: readableEventTime(event.installationStart, event.installationEnd), expectedGuests: String(source.expectedGuests ?? '-'), coordinator: source.coordinator || '-', venueContact: source.venueContact || '-', created: formatDate(source.created), lastUpdated: formatDate(source.lastUpdated), overview: source.overview || event.moodPlan || '-', rows }
  const lifecycleKnown = rows.some((row) => row.lifecycleKnown)
  const doc = new jsPDF({ unit: 'pt', format: 'letter', orientation: 'portrait' }); const totals = data.rows.reduce((a, r) => ({ planned: a.planned + r.planned, deployed: typeof r.deployed === 'number' ? a.deployed + r.deployed : a.deployed, returned: typeof r.returned === 'number' ? a.returned + r.returned : a.returned, damaged: typeof r.damaged === 'number' ? a.damaged + r.damaged : a.damaged, lost: typeof r.lost === 'number' ? a.lost + r.lost : a.lost }), { planned: 0, deployed: 0, returned: 0, damaged: 0, lost: 0 }); const metric = (value: number, known: boolean) => known ? String(value) : '-'; const pending = lifecycleKnown ? Math.max(totals.planned - totals.deployed, 0) : '-'; let y = 57.5
  const newPage = () => { footer(doc, data.reference); doc.addPage(); header(doc); y = 57.5 }
  const ensure = (height: number) => { if (y + height > 720) newPage() }
  header(doc); text(doc, 'LUMIÈRE', 306, y + 22, 30, DOCX_SPEC.colors.accent, 'times', 'bold', 'center'); doc.setCharSpace(1.2); doc.setFont('times', 'bold'); doc.setFontSize(TYPE.subtitle); doc.setTextColor(...rgb(DOCX_SPEC.colors.ink)); doc.text('EVENT ASSET & LOGISTICS REPORT', 306, y + 43, { align: 'center' }); resetTextState(doc); y += 56
  const stripW = 167.333; [['EVENT REFERENCE', data.reference], ['GENERATED', data.generated], ['STATUS', data.status]].forEach(([l, v], i) => cell(doc, 55 + i * stripW, y, stripW, 42, l, v, 'bold', true)); y += 60
  heading(doc, '1. EVENT INFORMATION', y); y += 9; const info = [['EVENT NAME', data.title], ['CLIENT', data.client], ['VENUE', data.venue], ['EVENT TYPE', data.eventType], ['EVENT DATE', data.eventDate], ['EVENT TIME', data.eventTime], ['EXPECTED GUESTS', data.expectedGuests], ['EVENT STATUS', data.status], ['EVENT COORDINATOR', data.coordinator], ['VENUE CONTACT', data.venueContact], ['CREATED', data.created], ['LAST UPDATED', data.lastUpdated]]; for (let r = 0; r < 3; r++) { const row = info.slice(r * 4, r * 4 + 4); const rowHeight = Math.max(...row.map((pair) => valueHeight(doc, pair[1], 125.5))); row.forEach((pair, c) => cell(doc, 55 + c * 125.5, y, 125.5, rowHeight, pair[0], pair[1])); y += rowHeight } y += 8
  y += 14; heading(doc, '2. EVENT OVERVIEW', y); y += 14; const overview = doc.splitTextToSize(data.overview, 502); text(doc, overview.join('\n'), 55, y, TYPE.overview, DOCX_SPEC.colors.ink, 'times', 'italic'); y += overview.length * 11 + 17
  heading(doc, '3. ASSET SUMMARY', y); y += 9; const stats = [['PLANNED', totals.planned, DOCX_SPEC.colors.accent], ['DEPLOYED', lifecycleKnown ? totals.deployed : '-', DOCX_SPEC.colors.accent], ['RETURNED', lifecycleKnown ? totals.returned : '-', DOCX_SPEC.colors.accent], ['DAMAGED', lifecycleKnown ? totals.damaged : '-', DOCX_SPEC.colors.amber], ['MISSING / LOST', lifecycleKnown ? totals.lost : '-', DOCX_SPEC.colors.red], ['PENDING', pending, DOCX_SPEC.colors.accent]] as const; stats.forEach(([label, value, color], i) => { const x = 55 + i * 83.666; panel(doc, x, y, 83.666, 42); text(doc, String(value), x + 41.833, y + 22, TYPE.summaryNumber, color, SUMMARY_FONT_FAMILY, 'bold', 'center'); text(doc, label, x + 41.833, y + 34, TYPE.summaryLabel, color, 'times', 'bold', 'center') }); y += 61; footer(doc, data.reference); doc.addPage(); header(doc); y = 57.5
  heading(doc, '4. ASSETS DEPLOYED', y); y += 12; const columns = [['ASSET', 140], ['CLASS', 76], ['PLANNED', 45], ['DEPLOYED', 45], ['RETURNED', 45], ['DAMAGED', 45], ['LOST', 38], ['STATUS', 68]] as const; const assetTableY = y; panel(doc, 55, y, 502, 21); doc.setFillColor(...rgb(DOCX_SPEC.colors.accent)); doc.rect(55, y, 502, 21, 'F'); let x = 55; columns.forEach(([label, width], i) => { if (i > 0) { doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.setLineWidth(0.45); doc.line(x, y, x, y + 21); resetTextState(doc) } text(doc, label, i >= 2 ? x + width / 2 : x + DOCX_SPEC.assets.cellMargins, y + 14, Math.min(DOCX_SPEC.assets.headerSize, i >= 2 ? 7 : 8), DOCX_SPEC.colors.white, 'times', 'bold', i >= 2 ? 'center' : 'left'); x += width }); y += 21
  data.rows.forEach(row => { ensure(25); x = 55; const rowHasLifecycle = row.lifecycleKnown === true; const values = [row.asset, row.className, `${row.planned}`, `${row.deployed}`, `${row.returned}`, `${row.damaged}`, `${row.lost}`, rowHasLifecycle ? statusFor(row).label : '-']; values.forEach((value, i) => { const width = columns[i][1]; text(doc, value, i >= 2 ? x + width / 2 : x + DOCX_SPEC.assets.cellMargins, y + 16, DOCX_SPEC.assets.bodySize, i === 7 && rowHasLifecycle ? statusFor(row).color : DOCX_SPEC.colors.ink, 'times', i === 7 && rowHasLifecycle ? 'bold' : 'normal', i >= 2 ? 'center' : 'left'); x += width }); doc.setDrawColor(...rgb(DOCX_SPEC.colors.border)); doc.setLineWidth(0.45); doc.line(55, y, 557, y); x = 55; columns.forEach(([, width]) => { x += width; if (x < 557) doc.line(x, y, x, y + 25) }); doc.line(55, y + 25, 557, y + 25); y += 25 }); borderOnly(doc, 55, assetTableY, 502, y - assetTableY); y += 18
  ensure(230); heading(doc, '5. LOGISTICS INFORMATION', y); y += 17; const logistics = [['DISPATCH', 'September 20, 2026 — 8:00 AM', 'Warehouse', 'Loading'], ['TRANSIT', 'September 20, 2026 — 9:15 AM', 'In Transit', ''], ['INGRESS', 'September 20, 2026 — 10:10 AM', 'Arrived at Venue', ''], ['SETUP', 'September 20, 2026 — 11:00 AM', 'Setup Completed', ''], ['EVENT', 'September 20, 2026 — 6:00 PM', 'Event Started', ''], ['EGRESS', 'September 21, 2026 — 12:15 AM', 'Post-Event Inspection', ''], ['RETURN', 'September 21, 2026 — 2:00 AM', 'Assets Returned', '']] as const; logistics.forEach(([stage, timestamp, description, destination], i) => { ensure(i < logistics.length - 1 ? 52 : 30); const y0 = y; text(doc, stage, 70, y0 + 10, TYPE.timelineTitle, DOCX_SPEC.colors.accent, 'times', 'bold'); text(doc, timestamp, 70, y0 + 24, 9.5, DOCX_SPEC.colors.ink, 'times', 'normal'); text(doc, '—', 228, y0 + 24, 9.5, DOCX_SPEC.colors.accent, 'times', 'normal', 'center'); if (destination) { text(doc, description, 242, y0 + 24, 9, DOCX_SPEC.colors.muted, 'times', 'italic'); const descriptionWidth = doc.getTextWidth(description); drawLineArrow(doc, 242 + descriptionWidth + 5, y0 + 21, 242 + descriptionWidth + 19); text(doc, destination, 242 + descriptionWidth + 24, y0 + 24, 9, DOCX_SPEC.colors.muted, 'times', 'italic') } else text(doc, description, 242, y0 + 24, 9, DOCX_SPEC.colors.muted, 'times', 'italic'); if (i < logistics.length - 1) { drawDownArrow(doc, 70, y0 + 30); y = y0 + 52 } else y = y0 + 30 });
  ensure(90); y += 26; text(doc, 'TRANSPORT INFORMATION', 55, y, 9, DOCX_SPEC.colors.muted, 'times', 'bold'); doc.setDrawColor(...rgb(DOCX_SPEC.colors.ink)); doc.setLineWidth(DOCX_SPEC.headings.bottomBorderWidth); doc.line(55, y + 4, 557, y + 4); resetTextState(doc); y += 15; const transport = [['VEHICLE', '-'], ['DRIVER', '-'], ['DISPATCH', '-'], ['VENUE ARRIVAL', '-'], ['RETURN', '-'], ['CREW', '-']]; for (let r = 0; r < 2; r++) { const row = transport.slice(r * 3, r * 3 + 3); const rowHeight = Math.max(...row.map((pair) => valueHeight(doc, pair[1], 167.333))); row.forEach((pair, c) => cell(doc, 55 + c * 167.333, y, 167.333, rowHeight, pair[0], pair[1])); y += rowHeight } y += 8; footer(doc, data.reference); doc.addPage(); header(doc); y = 57.5
  const emptySection = (title: string) => { heading(doc, title, y); y += 18; text(doc, 'No data recorded for this event yet.', 55, y, 8.5, DOCX_SPEC.colors.muted, 'times', 'italic'); y += 28 }
  emptySection('6. INGRESS'); emptySection('7. ON-SITE / SETUP'); emptySection('8. EGRESS & RETURN'); footer(doc, data.reference); doc.addPage(); header(doc); y = 57.5
  ensure(9 + 22 * 7 + 20); heading(doc, '9. ASSET RECONCILIATION', y); y += 9; [['METRIC', 'QUANTITY'], ['Planned', `${totals.planned}`], ['Deployed', metric(totals.deployed, lifecycleKnown)], ['Returned', metric(totals.returned, lifecycleKnown)], ['Damaged', metric(totals.damaged, lifecycleKnown)], ['Lost / Missing', metric(totals.lost, lifecycleKnown)], ['Pending Verification', `${pending}`]].forEach((row, i) => { const rowY = y + i * 22; if (i === 0) { doc.setFillColor(...rgb(DOCX_SPEC.colors.accent)); doc.setDrawColor(...rgb(DOCX_SPEC.colors.accent)); doc.rect(55, rowY, 502, 22, 'FD') } else { borderOnly(doc, 55, rowY, 377, 22); borderOnly(doc, 432, rowY, 125, 22) } text(doc, row[0], 62, rowY + 15, i === 0 ? TYPE.tableHeader : 10, i === 0 ? DOCX_SPEC.colors.white : DOCX_SPEC.colors.ink, 'times', 'bold'); text(doc, row[1], 494.5, rowY + 15, i === 0 ? TYPE.tableHeader : 10, i === 0 ? DOCX_SPEC.colors.white : DOCX_SPEC.colors.ink, 'times', 'bold', 'center') }); y += 22 * 7 + 20
  ensure(70); heading(doc, '10. DEFICIT / EXCEPTIONS', y); y += 20; text(doc, 'No deficit or exceptions recorded.', 55, y, TYPE.overview, DOCX_SPEC.colors.muted, 'times', 'italic'); text(doc, 'STATUS', 55, y + 22, TYPE.deficitLabel, DOCX_SPEC.colors.ink, 'times', 'bold'); text(doc, '-', 112, y + 22, TYPE.deficitValue, DOCX_SPEC.colors.amber, 'times', 'bold'); y += 52
  ensure(9 + 39 * 2 + 14); heading(doc, '11. CREW & RESPONSIBILITY', y); y += 9; const crew = [['EVENT COORDINATOR', '-'], ['CREW LEAD', '-'], ['DISPATCH CREW', '-'], ['SETUP CREW', '-'], ['EGRESS CREW', '-'], ['DRIVER', '-'], ['VENUE CONTACT', '-'], ['VEHICLE', '-']]; for (let r = 0; r < 2; r++) { const row = crew.slice(r * 4, r * 4 + 4); const rowHeight = Math.max(...row.map((pair) => valueHeight(doc, pair[1], 125.5)), 45); row.forEach((pair, c) => cell(doc, 55 + c * 125.5, y, 125.5, rowHeight, pair[0], pair[1])); y += rowHeight } y += 14
  ensure(9 + 45 * 4 + 120); y += 20; heading(doc, '12. AUDIT & VERIFICATION', y); y += 12; const audit = [['EVENT REFERENCE ID', data.reference], ['REPORT REFERENCE', data.reference.replace(/^[^-]+/, 'RPT')], ['GENERATED BY', 'System (Lumière)'], ['GENERATED TIMESTAMP', data.generated], ['LAST SYNCHRONIZATION', '-'], ['LAST MODIFIED', '-'], ['VERIFIED BY', '-'], ['VERIFICATION STATUS', '-']]; for (let r = 0; r < 4; r++) { const row = audit.slice(r * 2, r * 2 + 2); const rowHeight = Math.max(...row.map((pair) => valueHeight(doc, pair[1], 251)), 45); row.forEach((pair, c) => cell(doc, 55 + c * 251, y, 251, rowHeight, pair[0], pair[1])); y += rowHeight } y += 8; borderOnly(doc, 55, y, 70, 70); if (qrDataUrl) doc.addImage(qrDataUrl, 'PNG', 61, y + 6, 58, 58); else text(doc, 'QR', 90, y + 38, TYPE.qrTitle, DOCX_SPEC.colors.ink, 'times', 'bold', 'center'); text(doc, 'SCAN TO VERIFY EVENT RECORD', 140, y + 28, TYPE.qrTitle, DOCX_SPEC.colors.ink, 'times', 'bold'); text(doc, `Ref: ${data.reference}`, 140, y + 42, TYPE.qrReference, DOCX_SPEC.colors.muted, 'times', 'italic'); y += 84; text(doc, 'This report is a system-generated record of the Lumière event asset lifecycle and is provided for internal operations, accountability, and archival purposes.', 306, y, 8, DOCX_SPEC.colors.ink, 'times', 'italic', 'center')
footer(doc, data.reference); doc.putTotalPages('{total_pages_count_string}'); doc.save(`Lumiere_Event_Asset_Logistics_Report_${safeReference(data.reference)}.pdf`)
}

export { DOCX_SPEC }

// DOCX_SPEC is copied from the attached formatter: Letter geometry, 55/57.5 pt margins, 167.333 pt cells, 125.5 pt grids, 0.45/0.55 pt borders, and the specified palette/type scale.
// All later sections use the same fixed sample data and derive reconciliation values from the section 4 rows.
// jsPDF replaces the total-page placeholder at save time; vectors are used for timeline arrowheads.
