// <auto-generated />
using System;
using Lumiere.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumiere.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumiere.Core.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("AssetState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_state");

                    b.Property<Guid?>("AssetSubTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_sub_type_id");

                    b.Property<int>("AssetTier")
                        .HasColumnType("integer")
                        .HasColumnName("asset_tier");

                    b.Property<Guid?>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<int>("BaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("base_count");

                    b.Property<decimal?>("Circumference")
                        .HasColumnType("numeric")
                        .HasColumnName("circumference");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("item_description");

                    b.Property<decimal?>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<bool>("IsChangeableColor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_changeable_color");

                    b.Property<bool>("IsCircular")
                        .HasColumnType("boolean")
                        .HasColumnName("is_circular");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fragile");

                    b.Property<bool>("IsMonoColor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mono_color");

                    b.Property<bool>("IsMultiColor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multi_color");

                    b.Property<string>("ItemCallName")
                        .HasColumnType("text")
                        .HasColumnName("item_call_name");

                    b.Property<string>("KittingData")
                        .HasColumnType("jsonb")
                        .HasColumnName("kitting_data");

                    b.Property<string>("Material")
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_name");

                    b.Property<string>("Origin")
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<decimal?>("OriginalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("original_value");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Shape")
                        .HasColumnType("text")
                        .HasColumnName("shape");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.Property<decimal?>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("AssetSubTypeId");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("color_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<int>("ColorOrder")
                        .HasColumnType("integer")
                        .HasColumnName("color_order");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HexValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hex_value");

                    b.Property<string>("MaterialFinish")
                        .HasColumnType("text")
                        .HasColumnName("material_finish");

                    b.Property<string>("PaintBrand")
                        .HasColumnType("text")
                        .HasColumnName("paint_brand");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("asset_colors", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetMaintenanceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<decimal>("CumulativeRepairCost")
                        .HasColumnType("numeric")
                        .HasColumnName("cumulative_repair_cost");

                    b.Property<bool>("DepreciationFlagged")
                        .HasColumnType("boolean")
                        .HasColumnName("depreciation_flagged");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("MaintenanceNotes")
                        .HasColumnType("text")
                        .HasColumnName("maintenance_notes");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<decimal>("RepairCost")
                        .HasColumnType("numeric")
                        .HasColumnName("repair_cost");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EventId");

                    b.HasIndex("ReportId");

                    b.ToTable("asset_maintenance_history", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("res_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_provisional");

                    b.Property<DateTimeOffset>("LockEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_end");

                    b.Property<DateTimeOffset>("LockStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_start");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.Property<Guid>("ReservedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reserved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EventId");

                    b.HasIndex("ReservedBy");

                    b.ToTable("asset_reservations", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetSubType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("asset_sub_type_id");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_sub_type_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("asset_sub_types", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TagValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("asset_tags", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("asset_types", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetVendor", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("RentalCost")
                        .HasColumnType("numeric")
                        .HasColumnName("rental_cost");

                    b.Property<DateTime?>("RentalPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rental_period_end");

                    b.Property<DateTime?>("RentalPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rental_period_start");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AssetId", "VendorId");

                    b.HasIndex("VendorId");

                    b.ToTable("asset_vendors", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid?>("AffectedRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_record_id");

                    b.Property<string>("AffectedTable")
                        .HasColumnType("text")
                        .HasColumnName("affected_table");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<string>("NewState")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_state");

                    b.Property<string>("PreviousState")
                        .HasColumnType("jsonb")
                        .HasColumnName("previous_state");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.BlacklistedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jti");

                    b.HasKey("Id");

                    b.ToTable("blacklisted_tokens", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.DamageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("CustodyMode")
                        .HasColumnType("text")
                        .HasColumnName("custody_mode");

                    b.Property<int>("DamagedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("damaged_quantity");

                    b.Property<string>("EmergencyUnblockMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("emergency_unblock_metadata");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ExifMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("exif_metadata");

                    b.Property<string>("FirstSignOff")
                        .HasColumnType("jsonb")
                        .HasColumnName("first_sign_off");

                    b.Property<bool>("IsTemporallyValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_temporally_valid");

                    b.Property<string>("LiabilityParty")
                        .HasColumnType("text")
                        .HasColumnName("liability_party");

                    b.Property<Guid?>("LinkedExceptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_exception_id");

                    b.Property<bool>("NoPhotographicEvidence")
                        .HasColumnType("boolean")
                        .HasColumnName("no_photographic_evidence");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<decimal?>("RepairCostEstimate")
                        .HasColumnType("numeric")
                        .HasColumnName("repair_cost_estimate");

                    b.Property<string>("ReportStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_status");

                    b.Property<string>("SecondSignOff")
                        .HasColumnType("jsonb")
                        .HasColumnName("second_sign_off");

                    b.Property<string>("SelfValidationRecord")
                        .HasColumnType("jsonb")
                        .HasColumnName("self_validation_record");

                    b.Property<DateTime?>("SettlementDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settlement_due_at");

                    b.Property<string>("Severity")
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256_hash");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<string>("SupervisorVerdict")
                        .HasColumnType("text")
                        .HasColumnName("supervisor_verdict");

                    b.Property<DateTime?>("VerdictAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verdict_at");

                    b.Property<Guid?>("VerdictBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verdict_by");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EventId");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("VerdictBy");

                    b.ToTable("damage_reports", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.DeficitQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("deficit_id");

                    b.Property<string>("AssetDescription")
                        .HasColumnType("text")
                        .HasColumnName("asset_description");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("BackupVendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("backup_vendor_id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal?>("CostPerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_per_unit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentStock")
                        .HasColumnType("integer")
                        .HasColumnName("current_stock");

                    b.Property<string>("DeficitStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deficit_status");

                    b.Property<int?>("EtaHours")
                        .HasColumnType("integer")
                        .HasColumnName("eta_hours");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("FlaggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flagged_at");

                    b.Property<Guid>("FlaggedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("flagged_by");

                    b.Property<string>("PoRef")
                        .HasColumnType("text")
                        .HasColumnName("po_ref");

                    b.Property<Guid?>("PrimaryVendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_vendor_id");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int>("QuantityNeeded")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_needed");

                    b.Property<int?>("ReorderQty")
                        .HasColumnType("integer")
                        .HasColumnName("reorder_qty");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Supplier")
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.Property<bool?>("TaggedForDispatch")
                        .HasColumnType("boolean")
                        .HasColumnName("tagged_for_dispatch");

                    b.Property<int?>("Threshold")
                        .HasColumnType("integer")
                        .HasColumnName("threshold");

                    b.Property<string>("TriggerSource")
                        .HasColumnType("text")
                        .HasColumnName("trigger_source");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("BackupVendorId");

                    b.HasIndex("EventId");

                    b.HasIndex("FlaggedBy");

                    b.HasIndex("PrimaryVendorId");

                    b.HasIndex("ResolvedBy");

                    b.ToTable("deficit_queue", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.DispatchPreparationQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("prep_queue_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<Guid>("CanvasId")
                        .HasColumnType("uuid")
                        .HasColumnName("canvas_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("PrepNotes")
                        .HasColumnType("text")
                        .HasColumnName("prep_notes");

                    b.Property<string>("PrepStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prep_status");

                    b.Property<int>("QuantityRequired")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_required");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CanvasId");

                    b.HasIndex("EventId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("dispatch_preparation_queue", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.EphemeralPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("perm_id");

                    b.Property<string>("AuthReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_timestamp");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_timestamp");

                    b.Property<Guid>("TempRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("temp_role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GrantedBy");

                    b.HasIndex("TempRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("ephemeral_permissions", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("BrandingAndTextures")
                        .HasColumnType("text")
                        .HasColumnName("branding_and_textures");

                    b.Property<string>("ColorPalette")
                        .HasColumnType("text")
                        .HasColumnName("color_palette");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateOfEvent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_event");

                    b.Property<decimal?>("EstimatedRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_revenue");

                    b.Property<string>("EventPegs")
                        .HasColumnType("text")
                        .HasColumnName("event_pegs");

                    b.Property<string>("EventVenue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_venue");

                    b.Property<TimeSpan>("FullStop")
                        .HasColumnType("interval")
                        .HasColumnName("full_stop");

                    b.Property<string>("GeoClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geo_class");

                    b.Property<DateTime>("IngressDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingress_date");

                    b.Property<TimeSpan>("IngressTime")
                        .HasColumnType("interval")
                        .HasColumnName("ingress_time");

                    b.Property<bool>("IsLossMaker")
                        .HasColumnType("boolean")
                        .HasColumnName("is_loss_maker");

                    b.Property<DateTime>("MobilizationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mobilization_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("return_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TransitBufferDays")
                        .HasColumnType("integer")
                        .HasColumnName("transit_buffer_days");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.EventCanvas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("canvas_id");

                    b.Property<string>("AnnotationState")
                        .HasColumnType("jsonb")
                        .HasColumnName("annotation_state");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("CanvasMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canvas_mode");

                    b.Property<string>("CanvasState")
                        .HasColumnType("jsonb")
                        .HasColumnName("canvas_state");

                    b.Property<string>("CanvasStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canvas_status");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("SubmittedBy");

                    b.ToTable("event_canvases", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.EventFinancials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("financial_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EstimatedAssetCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_asset_cost");

                    b.Property<decimal>("EstimatedGrossMargin")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_gross_margin");

                    b.Property<decimal?>("EstimatedRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_revenue");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsLossMaker")
                        .HasColumnType("boolean")
                        .HasColumnName("is_loss_maker");

                    b.Property<DateTime?>("LossMakerAcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loss_maker_acknowledged_at");

                    b.Property<Guid?>("LossMakerAcknowledgedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("loss_maker_acknowledged_by");

                    b.Property<decimal>("QuotationAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("quotation_amount");

                    b.Property<decimal>("TotalConsumableCosts")
                        .HasColumnType("numeric")
                        .HasColumnName("total_consumable_costs");

                    b.Property<decimal>("TotalDamageCosts")
                        .HasColumnType("numeric")
                        .HasColumnName("total_damage_costs");

                    b.Property<decimal>("TotalEmergencyPurchases")
                        .HasColumnType("numeric")
                        .HasColumnName("total_emergency_purchases");

                    b.Property<decimal>("TotalLaborCosts")
                        .HasColumnType("numeric")
                        .HasColumnName("total_labor_costs");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("LossMakerAcknowledgedBy");

                    b.ToTable("event_financials", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.EventViewer", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_level");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("viewer_id");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("GrantedBy");

                    b.HasIndex("RevokedBy");

                    b.HasIndex("UserId");

                    b.ToTable("event_viewers", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.FieldReportQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ClientTxId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_tx_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ClientTxId")
                        .IsUnique();

                    b.HasIndex("EventId");

                    b.HasIndex("SubmittedBy");

                    b.ToTable("field_report_queue_items", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.InvestigationTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("AutoExpireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_expire_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("TicketStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EventId");

                    b.HasIndex("ReportId");

                    b.HasIndex("ResolvedBy");

                    b.ToTable("investigation_tickets", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.ManningAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_override");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shift_date");

                    b.Property<TimeSpan?>("ShiftEndTime")
                        .HasColumnType("interval")
                        .HasColumnName("shift_end_time");

                    b.Property<TimeSpan?>("ShiftStartTime")
                        .HasColumnType("interval")
                        .HasColumnName("shift_start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("manning_assignments", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("TargetRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_role_id");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.ProductionQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyTargetUnits")
                        .HasColumnType("integer")
                        .HasColumnName("daily_target_units");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("production_quotas", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.ProductionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("CompletedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("completed_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("progress_percentage");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TargetQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("target_quantity");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("EventId");

                    b.ToTable("production_tasks", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<bool>("AllowSelfValidation")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_self_validation");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("role_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor_name");

                    b.Property<string>("VendorNotes")
                        .HasColumnType("text")
                        .HasColumnName("vendor_notes");

                    b.HasKey("Id");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.VendorContactNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("contact_number_id");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NumberLabel")
                        .HasColumnType("text")
                        .HasColumnName("number_label");

                    b.Property<Guid>("RepresentativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RepresentativeId");

                    b.ToTable("vendor_contact_numbers", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.VendorContactPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PlatformType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform_type");

                    b.Property<string>("PlatformValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform_value");

                    b.Property<Guid>("RepresentativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RepresentativeId");

                    b.ToTable("vendor_contact_platforms", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.VendorRepresentative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("representative_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("representative_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("vendor_representatives", (string)null);
                });

            modelBuilder.Entity("Lumiere.Core.Entities.Asset", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.AssetSubType", "AssetSubType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetSubTypeId");

                    b.HasOne("Lumiere.Core.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId");

                    b.Navigation("AssetSubType");

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetColor", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany("Colors")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetMaintenanceHistory", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.DamageReport", "DamageReport")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("DamageReport");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetReservation", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "Reserver")
                        .WithMany()
                        .HasForeignKey("ReservedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Event");

                    b.Navigation("Reserver");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetSubType", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.AssetType", "AssetType")
                        .WithMany("SubTypes")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetTag", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany("Tags")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetVendor", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany("Vendors")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.DamageReport", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "VerdictIssuer")
                        .WithMany()
                        .HasForeignKey("VerdictBy");

                    b.Navigation("Asset");

                    b.Navigation("Event");

                    b.Navigation("Submitter");

                    b.Navigation("VerdictIssuer");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.DeficitQueue", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("Lumiere.Core.Entities.Vendor", "BackupVendor")
                        .WithMany()
                        .HasForeignKey("BackupVendorId");

                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "Flagger")
                        .WithMany()
                        .HasForeignKey("FlaggedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.Vendor", "PrimaryVendor")
                        .WithMany()
                        .HasForeignKey("PrimaryVendorId");

                    b.HasOne("Lumiere.Core.Entities.User", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy");

                    b.Navigation("Asset");

                    b.Navigation("BackupVendor");

                    b.Navigation("Event");

                    b.Navigation("Flagger");

                    b.Navigation("PrimaryVendor");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.DispatchPreparationQueue", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedTo");

                    b.HasOne("Lumiere.Core.Entities.EventCanvas", "Canvas")
                        .WithMany()
                        .HasForeignKey("CanvasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "LastUpdater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Asset");

                    b.Navigation("AssignedStaff");

                    b.Navigation("Canvas");

                    b.Navigation("Event");

                    b.Navigation("LastUpdater");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.EphemeralPermission", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.User", "Grantor")
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.Role", "TempRole")
                        .WithMany()
                        .HasForeignKey("TempRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grantor");

                    b.Navigation("TempRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.EventCanvas", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithOne()
                        .HasForeignKey("Lumiere.Core.Entities.EventCanvas", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmittedBy");

                    b.Navigation("Approver");

                    b.Navigation("Event");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.EventFinancials", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithOne()
                        .HasForeignKey("Lumiere.Core.Entities.EventFinancials", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "Acknowledger")
                        .WithMany()
                        .HasForeignKey("LossMakerAcknowledgedBy");

                    b.Navigation("Acknowledger");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.EventViewer", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "Grantor")
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "Revoker")
                        .WithMany()
                        .HasForeignKey("RevokedBy");

                    b.HasOne("Lumiere.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Grantor");

                    b.Navigation("Revoker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.FieldReportQueueItem", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Event");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.InvestigationTicket", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("Lumiere.Core.Entities.DamageReport", "DamageReport")
                        .WithMany()
                        .HasForeignKey("ReportId");

                    b.HasOne("Lumiere.Core.Entities.User", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy");

                    b.Navigation("Asset");

                    b.Navigation("DamageReport");

                    b.Navigation("Event");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.ManningAssignment", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.ProductionTask", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("Lumiere.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.User", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.VendorContactNumber", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.VendorRepresentative", "Representative")
                        .WithMany("ContactNumbers")
                        .HasForeignKey("RepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.VendorContactPlatform", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.VendorRepresentative", "Representative")
                        .WithMany("Platforms")
                        .HasForeignKey("RepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.VendorRepresentative", b =>
                {
                    b.HasOne("Lumiere.Core.Entities.Vendor", "Vendor")
                        .WithMany("Representatives")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.Asset", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Tags");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetSubType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.AssetType", b =>
                {
                    b.Navigation("SubTypes");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.Vendor", b =>
                {
                    b.Navigation("Representatives");
                });

            modelBuilder.Entity("Lumiere.Core.Entities.VendorRepresentative", b =>
                {
                    b.Navigation("ContactNumbers");

                    b.Navigation("Platforms");
                });
#pragma warning restore 612, 618
        }
    }
}
